### ISSUE TITLE
Should add libpg, libsql, and gems to avoid horrible relinking issues

### ISSUE THREAD

**Issue by scotthain** [chef/omnibus-chef#357]
As seen many times before, when system libpg or libsql is installed and chef (or chefdk)'s ruby is used to install the pg gem, it ends up failing due to differences in the version of openssl that it links against.

Adding these libraries and gems should remove the possibility of this relatively common and hard to diagnose/fix issue.

@lamont-granquist

**Comment by lamont-granquist** [comment]
Yeah, we didn't include these with omnibus because we felt they would be linked to the software the user is running or versions that they have on their systems.

This turns into a PITA though since if we're trying to install a chef_gem which needs to link against the system mysql/pg libs then it also has to be forced into linking against the system openssl and the solution to that are pretty terrible and brittle, they broke in 12.0.0, and even after sorting that out, users still run into headaches getting the system setup properly to install the gems.

I feel like we should reconsider shipping omnibus-chef and chefdk with the mysql and postgres c libraries and the mysql2 and pg gems pre-installed.  The only downside to doing this is that they won't necessarily match the version of the server that the users are running, but as long as we're bumping the version numbers aggressively then we should be able to rely on backcompat, and both protocols are fairly stable anyway.  I doubt anyone will notice any issues, and if anyone does hit an edge condition where it doesn't work for them the overall impact will be much less than the pain that is caused to everyone trying to manage mysql/pg database with chef.

**Comment by lamont-granquist** [comment]
^ to be clearer, my only concern is that if we ship the latest pg gem with 9.4.1 pg-libs (the current as of today), that users will be able to manage, say, postgres 8.x and 9.x servers with that client side configuration without issues.

**Comment by lamont-granquist** [comment]
And see https://github.com/chef/omnibus-sync/blob/master/config/software/postgresql-libs.rb

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef-rfc/blob/master/rfc063-omnibus-chef-native-gems.md
