### ISSUE TITLE
Chef 12.4.0 added pulled in cheffish to the DSL by default

### ISSUE THREAD

**Issue by b-dean** [chef/omnibus-chef#426]
I'm running into problems because `cheffish` is installed, but I don't know why it would be since it's a development dependency of chef, I wouldn't expect it to be installed. 

The problem I'm having is that in `some_cookbook/libraries/something.rb` I have a method `something()` that has a variable `chef_node`. This `something()` method gets included in `Chef::Recipe` and then I get an error `"You must supply a name when declaring a chef_node resource"`

I figured out that the `chef_node` resource is defined by the `cheffish` gem, which is a development dependency of `chef`. On older versions of chef (less than 12.3.0) I could run:

```
chef-apply -e "puts Chef::Resource.const_defined?(:ChefNode)"
```

and the output would be `false`. But now it's true. And I looked around in the `/opt/chef directory` for cheffish and found it in `/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2/`

There other development dependencies there too such as rack, rake, and rspec.

This seems like it's omnibus-chef problem so I made the issue here.

**Comment by lamont-granquist** [comment]
The dev dependencies must be installed, that's by design so that when we test the omnibus package we use the bundled dev gems and test against a known target.  We had many failures due to bundle installing over the omnibus-chef repo and running the specs against the result of that rather than the shipped bundle.

It looks like cheffish was made automatically included by this commit but was intended to be optional:

https://github.com/chef/chef/commit/bf6340a113dd0c37e2084c70007d201742f11e9d

Then while it was intended to be only for dev rspec tests, this commit added cheffish which made it no longer optional effectively a mandatory part of the DSL:

https://github.com/chef/chef/commit/644342358dcd7202c24f731eae498db1ec46db3d

**Comment by b-dean** [comment]
ok ... so since it's part of the dsl now, that means we have to make sure not to name variables the same as resources inside recipes, just like with any other resource.

**Comment by lamont-granquist** [comment]
Updated the title.  We have to ship the dev gems with the product, that is not the bug.

**Comment by b-dean** [comment]
I saw the same thing in 12.3.0 too. I thought it was just 12.4.0 but I checked again. I'm guessing that this isn't a thing to "fix" since you just want cheffish to always be there now.

**Comment by lamont-granquist** [comment]
Yeah, it was unintentional to do this in 12.4.0 but there was probably an inevitable collision that was going to occur sooner or later here.  Since there's no namespacing if we extend the DSL in any way we always risk clobbering someone.  We can play the game of only allowing this on major version upgrades but that means that from a software dev perspective we'd like to be doing major version bumps every 6 month or faster which would drive users crazy.  It then pushes all kinds of breaking changes into panic 6-8 month long coding sessions when the major version change opens up, and if we miss anything then we can't fix it until the next major version change.

But whatever argument you'd like to make about that, your code would always conflict with cheffish if it ever did get included together and with the direction we're going its likely that we'd ship it together with the client sooner or later.  Better to fix the breakage now.

**Comment by jkeiser** [comment]
I am confused; if you name a variable "x", Ruby will not call the method "x", so you shouldn't be hitting this exact thing. What does the code look like that has this issue? Are you talking about a local variable here?

**Comment by b-dean** [comment]
Yeah it was a red herring. It was just stupid code something like ....

```ruby
# libraries/helper.rb
class Chef
  class Recipe
    def foo()
      puts chef_node['fqdn']
    end
  end
end
```

```ruby
# recipes/derp.rb
foo()
```

which then tries to make a resource out of that "local variable" `chef_node` ... but this is (like I said) stupid code and it really should be like this:

```ruby
# libraries/helper.rb
class Chef
  class Recipe
    def foo(chef_node = node)
      puts chef_node['fqdn']
    end
  end
end
```

I just saw that `chef_node` resource stuff and had just changed to 12.4.0 and thought something weird was happening and didn't look into it enough before I made the issue. Sorry :frowning: :-1: :facepunch:

**Comment by jkeiser** [comment]
No problem, glad you're past it!
