### ISSUE TITLE
Make Chef work with latest curl CA bundle and AWS S3 certificates

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/omnibus-chef#447]
Right now Chef [ships an old version of CA Certificates](https://github.com/chef/omnibus-chef/blob/chef-12.4.1/config/projects/chef.rb#L41-L51) to get around the s3.amazonaws.com being issued by a Root CA that is no longer shipped in the [CA Cert bundle](http://curl.haxx.se/ca/cacert.pem). However, this creates other problems when Chef can't trust certificates that are generated by newer root CAs that are not included in the older CA bundle.

Reference: https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/9148300-front-s3-downloads-with-cloudfront-and-custom-ssl

Let's get a release of Chef that uses the newer CA bundle and modifies it to also work for AWS S3 certificates.

**Comment by lamont-granquist** [comment]
Since the only issue we current have and have had with the cert bundle is with the specific AWS S3 cert, the minimum viable product that will solve this issue is most likely to fix is just for the AWS certa and to download the current cacert bundle and append the cert they are removing.

We could import the perl script and hack it up to our liking but that will be more work, and while that would solve any future issues as well so far we've only ever seen this problem with this one cert, so YAGNI.
