### ISSUE TITLE
Bump rubygems back to 2.4.8

### ISSUE THREAD

**Issue by jkeiser** [chef/omnibus-chef#483]
The latest version has a security patch, and handles our `universal` packages better for Windows and OS/X.

**Comment by tyler-ball** [comment]
2.4.8 was causing an issue with loading files multiple times.  Thats why we reverted to 2.4.4 in https://github.com/chef/omnibus-chef/pull/482

**Comment by lamont-granquist** [comment]
Based on @jkeiser's comments in slack it looks like the revert to 2.4.4 is the wrong patch.  The right solution is to figure out why the load path is being changed and why resource_notifications.rb is being pulled in from different gems.  If that's incorrect, then we should have more information on what the bug is in rubygems which is causing the problem and need to have a bug cut against rubygems with the details.

And the depsolver in 2.4.4 is *broken* and currently is causing issues with being unable to prune the ohai-8.6.0 gem out of solution sets, while 2.4.8 works.

And based on the description in slack, I'm wondering if they fixed something in 2.4.8 which exposed that we always had a bug here.

**Comment by tyler-ball** [comment]
We could also change `resource_notifications.rb` to not subclass `Struct.new` - I'm not sure where I came up with that little gem

**Comment by jkeiser** [comment]
@tyler-ball yeah, we should probably do that anyway so that people can open up that namespace ... but @danielsdeleo fixed us up proper-like so we don't double-load stuff :)

**Comment by jkeiser** [comment]
(Fixed.)
